### ISSUE TITLE
npm run visualization Issue

### ISSUE THREAD

**Issue by sntshred** [qlik-oss/core-get-started#175]
### Description

Npm run Visualization is erroring out 

### Steps to Reproduce

1. npm run hello-visualization 

##### Expected behavior

[What you expected to happen]
Expecting to get localhost URL of weback dev server, to view the visualization 

##### Actual behavior

[What actually happened]

> core-get-started@0.0.1 hello-visualization C:\Users\Santosh Chavan\Downloads\core-get-started-master
> webpack-dev-server --config ./src/hello-visualization/webpack.config.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-get-started@0.0.1 hello-visualization: `webpack-dev-server --config ./src/hello-visualization/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the core-get-started@0.0.1 hello-visualization script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

##### Library
```
[ ] Node.js

```
##### Operating system
```
[ ] Windows


### Versions

* Node.js: 
* Browser: 
* Operating system: 
* [Other relevant versions]

**Comment by peol** [comment]
Hi!

It looks like you may have another process listening on the `8080` port. What if you modify this line to another port (e.g. `8081`) and try again?

https://github.com/qlik-oss/core-get-started/blob/master/src/hello-visualization/webpack.config.js#L13

**Comment by sntshred** [comment]
Hello Peol,

Thanks for your help it got resolved the issue.
