### ISSUE TITLE
Security vulnerabilities in dependencies

### ISSUE THREAD

**Issue by flautrup** [qlik-oss/core-get-started#274]
### Description

During install of dependencies  14 vulnerabilities (3 moderate, 11 high) are reported.

### Steps to Reproduce

1. run npm install

##### Expected behavior

If possible use versions of dependencies with fixes to security problems

**Comment by axelssonHakan** [comment]
FYI:

These are "only" sub dependencies to **dev-dependencies** and we will bump these as soon as there are fixes released.
