### ISSUE TITLE
Investigate using Node.js from Docker image

### ISSUE THREAD

**Issue by peol** [qlik-oss/core-get-started#91]
To reduce the number of software needed on the users machine to get started. We could increase the success rate for newcomers this way, and just declare the Node.js version needed in the README if they want to run it locally.

If we want to use Docker images, we need to ensure that it mounts in the volume properly so changes are picked up (e.g. by `docker-compose up --build`).

**Comment by janmiderback** [comment]
Since it is targeting Qlik Core developers, the requirement to have Node.js and Docker on the dev machine seems pretty light. I'm not fully confident that running the example Node.js code in Docker makes things much easier for newcomers.
