### ISSUE TITLE
NPM install fail with npm 5.6.8

### ISSUE THREAD

**Issue by mountaindude** [qlik-oss/core-get-started#98]
Without thinking much of it, I upgraded npm to 5.8.0 before doing a "sudo npm install" (I am on Mac). 
That installation returns a "write after end" error though.

Downgrading npm to 5.6.0, then trying "sudo npm install" again, all works well.
Downgrading can be done using "npm install -g npm@5.6.0"

**Comment by wennmo** [comment]
Seems like a problem introduced in npm 5.7.x, see [here](https://github.com/npm/npm/issues/19989).

The latest LTS version of node (8.11.1) still includes npm 5.6.0.
